### ISSUE TITLE
Can't redirect back to main page from Manager layout

### ISSUE THREAD

**Issue by phathung2003** [GS-755/QLMB#6]
Can't handle redirect page from http://localhost:50762/Shared/Manager.

**Comment by GS-755** [comment]
I've explained to you that all of the PATH will be followed at RouteConfig.cs 
The reason is when you compile & run at ~/Views/Shared/Manager.cshtml, the default view of our project that uses this view IS NOT /Home/Index, so Manager.cshtml won't know where to call the dependent view by itself.

Surely, I'll close this issue. Thanks for reporting.

**Comment by GS-755** [comment]
"the default view of our project that uses this view IS NOT /Home/Index"
I have some mistakes, I mean "the default view of our project that uses this view is /Home/Index", that's not the view uses Manager.cshtml right? 
If we spend time configuring RouteConfig.cs, we wont have enough time to deal with the problem. 

Thanks for reporting. Sorry for my mistake.
